# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kilian/Documents/Cytometrie_en_flux

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kilian/Documents/Cytometrie_en_flux

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kilian/Documents/Cytometrie_en_flux/CMakeFiles /home/kilian/Documents/Cytometrie_en_flux//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kilian/Documents/Cytometrie_en_flux/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Cytometrie_en_flux

# Build rule for target.
Cytometrie_en_flux: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Cytometrie_en_flux
.PHONY : Cytometrie_en_flux

# fast build rule for target.
Cytometrie_en_flux/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/build
.PHONY : Cytometrie_en_flux/fast

#=============================================================================
# Target rules for targets named Cytometrie_en_flux_autogen

# Build rule for target.
Cytometrie_en_flux_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Cytometrie_en_flux_autogen
.PHONY : Cytometrie_en_flux_autogen

# fast build rule for target.
Cytometrie_en_flux_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux_autogen.dir/build.make CMakeFiles/Cytometrie_en_flux_autogen.dir/build
.PHONY : Cytometrie_en_flux_autogen/fast

Cytometrie_en_flux_autogen/mocs_compilation.o: Cytometrie_en_flux_autogen/mocs_compilation.cpp.o
.PHONY : Cytometrie_en_flux_autogen/mocs_compilation.o

# target to build an object file
Cytometrie_en_flux_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/Cytometrie_en_flux_autogen/mocs_compilation.cpp.o
.PHONY : Cytometrie_en_flux_autogen/mocs_compilation.cpp.o

Cytometrie_en_flux_autogen/mocs_compilation.i: Cytometrie_en_flux_autogen/mocs_compilation.cpp.i
.PHONY : Cytometrie_en_flux_autogen/mocs_compilation.i

# target to preprocess a source file
Cytometrie_en_flux_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/Cytometrie_en_flux_autogen/mocs_compilation.cpp.i
.PHONY : Cytometrie_en_flux_autogen/mocs_compilation.cpp.i

Cytometrie_en_flux_autogen/mocs_compilation.s: Cytometrie_en_flux_autogen/mocs_compilation.cpp.s
.PHONY : Cytometrie_en_flux_autogen/mocs_compilation.s

# target to generate assembly for a file
Cytometrie_en_flux_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/Cytometrie_en_flux_autogen/mocs_compilation.cpp.s
.PHONY : Cytometrie_en_flux_autogen/mocs_compilation.cpp.s

src/DataReader.o: src/DataReader.cpp.o
.PHONY : src/DataReader.o

# target to build an object file
src/DataReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/DataReader.cpp.o
.PHONY : src/DataReader.cpp.o

src/DataReader.i: src/DataReader.cpp.i
.PHONY : src/DataReader.i

# target to preprocess a source file
src/DataReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/DataReader.cpp.i
.PHONY : src/DataReader.cpp.i

src/DataReader.s: src/DataReader.cpp.s
.PHONY : src/DataReader.s

# target to generate assembly for a file
src/DataReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/DataReader.cpp.s
.PHONY : src/DataReader.cpp.s

src/DataStruct.o: src/DataStruct.cpp.o
.PHONY : src/DataStruct.o

# target to build an object file
src/DataStruct.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/DataStruct.cpp.o
.PHONY : src/DataStruct.cpp.o

src/DataStruct.i: src/DataStruct.cpp.i
.PHONY : src/DataStruct.i

# target to preprocess a source file
src/DataStruct.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/DataStruct.cpp.i
.PHONY : src/DataStruct.cpp.i

src/DataStruct.s: src/DataStruct.cpp.s
.PHONY : src/DataStruct.s

# target to generate assembly for a file
src/DataStruct.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/DataStruct.cpp.s
.PHONY : src/DataStruct.cpp.s

src/File.o: src/File.cpp.o
.PHONY : src/File.o

# target to build an object file
src/File.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/File.cpp.o
.PHONY : src/File.cpp.o

src/File.i: src/File.cpp.i
.PHONY : src/File.i

# target to preprocess a source file
src/File.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/File.cpp.i
.PHONY : src/File.cpp.i

src/File.s: src/File.cpp.s
.PHONY : src/File.s

# target to generate assembly for a file
src/File.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/File.cpp.s
.PHONY : src/File.cpp.s

src/GraphWindow.o: src/GraphWindow.cpp.o
.PHONY : src/GraphWindow.o

# target to build an object file
src/GraphWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/GraphWindow.cpp.o
.PHONY : src/GraphWindow.cpp.o

src/GraphWindow.i: src/GraphWindow.cpp.i
.PHONY : src/GraphWindow.i

# target to preprocess a source file
src/GraphWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/GraphWindow.cpp.i
.PHONY : src/GraphWindow.cpp.i

src/GraphWindow.s: src/GraphWindow.cpp.s
.PHONY : src/GraphWindow.s

# target to generate assembly for a file
src/GraphWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/GraphWindow.cpp.s
.PHONY : src/GraphWindow.cpp.s

src/QPlot.o: src/QPlot.cpp.o
.PHONY : src/QPlot.o

# target to build an object file
src/QPlot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/QPlot.cpp.o
.PHONY : src/QPlot.cpp.o

src/QPlot.i: src/QPlot.cpp.i
.PHONY : src/QPlot.i

# target to preprocess a source file
src/QPlot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/QPlot.cpp.i
.PHONY : src/QPlot.cpp.i

src/QPlot.s: src/QPlot.cpp.s
.PHONY : src/QPlot.s

# target to generate assembly for a file
src/QPlot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/QPlot.cpp.s
.PHONY : src/QPlot.cpp.s

src/VisualData.o: src/VisualData.cpp.o
.PHONY : src/VisualData.o

# target to build an object file
src/VisualData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/VisualData.cpp.o
.PHONY : src/VisualData.cpp.o

src/VisualData.i: src/VisualData.cpp.i
.PHONY : src/VisualData.i

# target to preprocess a source file
src/VisualData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/VisualData.cpp.i
.PHONY : src/VisualData.cpp.i

src/VisualData.s: src/VisualData.cpp.s
.PHONY : src/VisualData.s

# target to generate assembly for a file
src/VisualData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/VisualData.cpp.s
.PHONY : src/VisualData.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mainwindow.o: src/mainwindow.cpp.o
.PHONY : src/mainwindow.o

# target to build an object file
src/mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/mainwindow.cpp.o
.PHONY : src/mainwindow.cpp.o

src/mainwindow.i: src/mainwindow.cpp.i
.PHONY : src/mainwindow.i

# target to preprocess a source file
src/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/mainwindow.cpp.i
.PHONY : src/mainwindow.cpp.i

src/mainwindow.s: src/mainwindow.cpp.s
.PHONY : src/mainwindow.s

# target to generate assembly for a file
src/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/mainwindow.cpp.s
.PHONY : src/mainwindow.cpp.s

src/qcustomplot.o: src/qcustomplot.cpp.o
.PHONY : src/qcustomplot.o

# target to build an object file
src/qcustomplot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/qcustomplot.cpp.o
.PHONY : src/qcustomplot.cpp.o

src/qcustomplot.i: src/qcustomplot.cpp.i
.PHONY : src/qcustomplot.i

# target to preprocess a source file
src/qcustomplot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/qcustomplot.cpp.i
.PHONY : src/qcustomplot.cpp.i

src/qcustomplot.s: src/qcustomplot.cpp.s
.PHONY : src/qcustomplot.s

# target to generate assembly for a file
src/qcustomplot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cytometrie_en_flux.dir/build.make CMakeFiles/Cytometrie_en_flux.dir/src/qcustomplot.cpp.s
.PHONY : src/qcustomplot.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Cytometrie_en_flux_autogen"
	@echo "... Cytometrie_en_flux"
	@echo "... Cytometrie_en_flux_autogen/mocs_compilation.o"
	@echo "... Cytometrie_en_flux_autogen/mocs_compilation.i"
	@echo "... Cytometrie_en_flux_autogen/mocs_compilation.s"
	@echo "... src/DataReader.o"
	@echo "... src/DataReader.i"
	@echo "... src/DataReader.s"
	@echo "... src/DataStruct.o"
	@echo "... src/DataStruct.i"
	@echo "... src/DataStruct.s"
	@echo "... src/File.o"
	@echo "... src/File.i"
	@echo "... src/File.s"
	@echo "... src/GraphWindow.o"
	@echo "... src/GraphWindow.i"
	@echo "... src/GraphWindow.s"
	@echo "... src/QPlot.o"
	@echo "... src/QPlot.i"
	@echo "... src/QPlot.s"
	@echo "... src/VisualData.o"
	@echo "... src/VisualData.i"
	@echo "... src/VisualData.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mainwindow.o"
	@echo "... src/mainwindow.i"
	@echo "... src/mainwindow.s"
	@echo "... src/qcustomplot.o"
	@echo "... src/qcustomplot.i"
	@echo "... src/qcustomplot.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

